### ISSUE TITLE
Tutorial programs mislabel the split screen radio buttons

### ISSUE THREAD

**Issue by dougedmunds** [ToonTalk/behaviour-composer#983]
When in the composer running one of the tutorials such as the one that opens when clicking in the link on the page "A quick guide to using the Behaviour Composer"
in the line "A good beginning tutorial is this step-by-step guide to building an ecosystem of predators and prey."  it suggests scrolling to the bottom to split the screen.  

The radio buttons are not correctly labeled.   The 'horizontally' button splits the screen vertically, (creating a left -right split) and the "vertically' button splits the screen horizontally (creating an upper-lower split).
![capture](https://cloud.githubusercontent.com/assets/616048/9555433/e4388f0c-4d81-11e5-8232-90d1e771b1c9.PNG)
.

**Comment by ToonTalk** [comment]
Thanks for reporting this. Many people find this confusing (see #684). I just checked and Emacs works the same way as the Behaviour Composer. As does Java (https://docs.oracle.com/javase/tutorial/uiswing/components/splitpane.html).

When I Googled "split panes horizontally" I did find both points of view (didn't spend enough time to count enough to see which is more popular).

I think the confusion is whether one thinks of the window's horizontal dimension being split or whether one is adding a vertical splitter widget. To add to the confusion one can think of the action as creating horizontal or vertical panels.

In the next release the interface will be
![image](https://cloud.githubusercontent.com/assets/2138696/9561010/5d6f3c32-4e2b-11e5-98a0-56e0577b3007.png)

**Comment by dougedmunds** [comment]
Side-by-side is a good solution.  If you go to Home Depot and ask for 
'vertical' blinds,  you will see that they
are the kind attached at the top, side by side, not the ones that are 
layered one above the other..  If you look at a sunset 'on the horizon'  
the horizon is that left-to-right line, splitting the scene with land at 
the bottom and sky at top.
